/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/task": {
    /** Get all tasks with pagination and sorting */
    get: operations["getTasks"];
  };
  "/task/create": {
    /** Create a new task */
    post: operations["createTask"];
  };
  "/task/edit/{taskId}": {
    /** Update a task */
    patch: operations["updateTask"];
  };
  "/task/delete/{taskId}": {
    /** Delete a task */
    delete: operations["deleteTask"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Task: {
      /** @description Unique identifier for the task */
      _id: string;
      /** @description Title of the task */
      title: string;
      /** @description Description of the task */
      description: string;
      /** @description Completion status of the task */
      completed: boolean;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updatedAt: string;
    };
    Error: {
      /** @description Error message */
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get all tasks with pagination and sorting */
  getTasks: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: number;
        /** @description Number of tasks per page */
        limit?: number;
        /** @description Field to sort by */
        sortBy?: "createdAt" | "completed";
        /** @description Sort order */
        sortOrder?: "asc" | "desc";
        /** @description Filter by completion status (true for completed, false for not completed) */
        completed?: boolean;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            tasks?: components["schemas"]["Task"][];
            /** @description Total number of tasks */
            total?: number;
            /** @description Current page */
            page?: number;
            /** @description Total number of pages */
            totalPages?: number;
          };
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Create a new task */
  createTask: {
    requestBody: {
      content: {
        "application/json": {
          title: string;
          description: string;
        };
      };
    };
    responses: {
      /** @description Task created successfully */
      201: {
        content: {
          "application/json": {
            message: string;
            task: components["schemas"]["Task"];
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Update a task */
  updateTask: {
    parameters: {
      path: {
        taskId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          title?: string;
          description?: string;
          completed?: boolean;
        };
      };
    };
    responses: {
      /** @description Task updated successfully */
      200: {
        content: {
          "application/json": {
            message: string;
            task: components["schemas"]["Task"];
          };
        };
      };
      /** @description Task not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Delete a task */
  deleteTask: {
    parameters: {
      path: {
        taskId: string;
      };
    };
    responses: {
      /** @description Task deleted successfully */
      200: {
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      /** @description Task not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
